<a href="https://colab.research.google.com/github/mabatalim/ItTralee_ML/blob/main/Copy_of_Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 4

For Assignment 4 , we will be going through the same dataset that we went through Practical 4 i.e Titanic Dataset. I have loaded the dataset here with this notebook. This assignment includes similar operation that we did on Practical with little bit of tweak. The description for each task is give with the instruction. Please fill the notebook with the correct code to complete the task and submit it.

**Importing libraries**

In [1]:
# importing libs
import numpy as np # lib for manipulating multi dimensional array
import pandas as pd  # data analysis lib
import matplotlib.pyplot as plt  # data viz lib
import seaborn as sns # data viz lib

**Loading Data**

In [2]:
train_data = pd.read_csv("https://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/train.csv")
test_data = pd.read_csv("https://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/test.csv")

In [3]:
train_data.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [4]:
test_data.head()

   PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S

[5 rows x 11 columns]

## Task 1

Selecting specific row and columns from the data frame. Select the rows from index 5 to 50 and select columns from index 1 to 6


Note : To select dataframe in pandas use df.iloc[rows_index,cols_index]

Your dataframe should look sth like this :
![Screenshot 2020-12-20 at 13.38.55.png]()

In [16]:
#your answer here
#df.iloc[rows_index,cols_index]
# selecting rows & cols
train_data.iloc[5:50,1:6]

    Survived  Pclass  ...     Sex   Age
5          0       3  ...    male   NaN
6          0       1  ...    male  54.0
7          0       3  ...    male   2.0
8          1       3  ...  female  27.0
9          1       2  ...  female  14.0
10         1       3  ...  female   4.0
11         1       1  ...  female  58.0
12         0       3  ...    male  20.0
13         0       3  ...    male  39.0
14         0       3  ...  female  14.0
15         1       2  ...  female  55.0
16         0       3  ...    male   2.0
17         1       2  ...    male   NaN
18         0       3  ...  female  31.0
19         1       3  ...  female   NaN
20         0       2  ...    male  35.0
21         1       2  ...    male  34.0
22         1       3  ...  female  15.0
23         1       1  ...    male  28.0
24         0       3  ...  female   8.0
25         1       3  ...  female  38.0
26         0       3  ...    male   NaN
27         0       1  ...    male  19.0
28         1       3  ...  female   NaN
29         0       3  ...    male   NaN
30         0       1  ...    male  40.0
31         1       1  ...  female   NaN
32         1       3  ...  female   NaN
33         0       2  ...    male  66.0
34         0       1  ...    male  28.0
35         0       1  ...    male  42.0
36         1       3  ...    male   NaN
37         0       3  ...    male  21.0
38         0       3  ...  female  18.0
39         1       3  ...  female  14.0
40         0       3  ...  female  40.0
41         0       2  ...  female  27.0
42         0       3  ...    male   NaN
43         1       2  ...  female   3.0
44         1       3  ...  female  19.0
45         0       3  ...    male   NaN
46         0       3  ...    male   NaN
47         1       3  ...  female   NaN
48         0       3  ...    male   NaN
49         0       3  ...  female  18.0

[45 rows x 5 columns]

## Task 2

Give count of the passenger in train_dataset grouped by Port they embarked from who survived i.e survived = 1

Your answer should look like this with number of passenger who survived from port S, C and Q

![Screenshot 2020-12-20 at 13.54.17.png]()

In [6]:
# hint to select passenger who survived i.e survived == 1
train_data[train_data['Survived']==1].head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[5 rows x 12 columns]

In [23]:
# Hint : To groupy by particular  column by column and get their count
train_data.groupby(['Embarked']).count()

          PassengerId  Survived  Pclass  Name  ...  Parch  Ticket  Fare  Cabin
Embarked                                       ...
C                 168       168     168   168  ...    168     168   168     69
Q                  77        77      77    77  ...     77      77    77      4
S                 644       644     644   644  ...    644     644   644    129

[3 rows x 11 columns]

In [43]:
# your answer here

train_data.groupby('Embarked')['Survived'].count()

Embarked
C    168
Q     77
S    644
Name: Survived, dtype: int64

## Task 3

**One hot Encoding**

Use one hot encoding to encode features/ columns like 



*   Sex
*   Pclass
*   Embarked

Hint:  First convert column into category type

```
df['col_name'].astype('category')
```

To conver to one hot encoding use pd.get_dummies

```
pd.get_dummies(df, columns=['col?names'])
```

In [48]:
# your answer here to convert sex col to one hot encoding
train_data['Sex'] = train_data['Sex'].astype('category')
train_data = pd.get_dummies(train_data, columns=['Sex'])
train_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Sex_female', 'Sex_male'],
      dtype='object')

In [49]:
# your answer here to convert pclass col to one hot encoding
train_data['Pclass'] = train_data['Pclass'].astype('category')
train_data = pd.get_dummies(train_data, columns=['Pclass'])
train_data.columns

Index(['PassengerId', 'Survived', 'Name', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked', 'Sex_female', 'Sex_male', 'Pclass_1',
       'Pclass_2', 'Pclass_3'],
      dtype='object')

In [50]:
# your answer here to convert Embarked col to one hot encoding
train_data['Embarked'] = train_data['Embarked'].astype('category')
train_data = pd.get_dummies(train_data, columns=['Embarked'])
train_data.columns

Index(['PassengerId', 'Survived', 'Name', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Sex_female', 'Sex_male', 'Pclass_1', 'Pclass_2',
       'Pclass_3', 'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

## Task 4

Dropping unnecessary columns. This task involves droppping following columns : 

*   Ticket
*   Name
*   PassengerId
*   Cabin

In [51]:
# your answer here
train_data.drop(labels=['Ticket', 'Name', 'PassengerId','Cabin'], axis=1 , inplace = True) # axis 1 = column 0 = row , inplace = whethere to overwrite
train_data.head()

   Survived   Age  SibSp  Parch  ...  Pclass_3  Embarked_C  Embarked_Q  Embarked_S
0         0  22.0      1      0  ...         1           0           0           1
1         1  38.0      1      0  ...         0           1           0           0
2         1  26.0      0      0  ...         1           0           0           1
3         1  35.0      1      0  ...         0           0           0           1
4         0  35.0      0      0  ...         1           0           0           1

[5 rows x 13 columns]

## Task 5

Dealing with missing values. This task involved handling missing values. Check if there any missing values and eliminate those missing values with either with mean or random values

In [52]:
# your answer here
np.isnan(train_data.any())

Survived      False
Age           False
SibSp         False
Parch         False
Fare          False
Sex_female    False
Sex_male      False
Pclass_1      False
Pclass_2      False
Pclass_3      False
Embarked_C    False
Embarked_Q    False
Embarked_S    False
dtype: bool

In [53]:
train_data.fillna(train_data.mean())

     Survived        Age  SibSp  ...  Embarked_C  Embarked_Q  Embarked_S
0           0  22.000000      1  ...           0           0           1
1           1  38.000000      1  ...           1           0           0
2           1  26.000000      0  ...           0           0           1
3           1  35.000000      1  ...           0           0           1
4           0  35.000000      0  ...           0           0           1
..        ...        ...    ...  ...         ...         ...         ...
886         0  27.000000      0  ...           0           0           1
887         1  19.000000      0  ...           0           0           1
888         0  29.699118      1  ...           0           0           1
889         1  26.000000      0  ...           1           0           0
890         0  32.000000      0  ...           0           1           0

[891 rows x 13 columns]

## Task 6

Splitting train and validation set . This task involves to splitting the original train set to train and validation set.

In [ ]:
# your answer here

In [113]:
# your answer here

from sklearn.model_selection import train_test_split

# Separate the input and output columns.
X = train_data.drop('Survived', axis=1)
# For the output, we'll use the Survived column
Y = train_data['Survived']

Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size=0.2, random_state=0)

In [114]:
##Verify Data

# summarizes X and Y shape
print(X.shape, Y.shape)
# summarizes Xtrain, Xtest, Ytrain, Ytest
print(Xtrain.shape, Xtest.shape, Ytrain.shape, Ytest.shape)

(891, 12) (891,)
(712, 12) (179, 12) (712,) (179,)

## Task 7

Fitting into machine learning model. Previously in practical we used logistic regression and SVC to classify/predict whether the given passenger would surivive or not. In this **Task 6**, use Decision tree classifer to predict whether the given passenger survives or not. Before fitting the dataset into model make sure that your data is cleaned properly that includes eliminating null data, converting all categorical columns into one hot encoding.

To learn more about Decision tree Classifier : https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

In [115]:
#your answer here

from sklearn import tree
from sklearn.model_selection import cross_val_score

dtc = tree.DecisionTreeClassifier()
dtc.fit(Xtrain, Ytrain)
dtc_acc = cross_val_score(dtc, Xtrain, Ytrain, cv=5, scoring='accuracy').mean()
dtc_recall = cross_val_score(dtc, Xtrain, Ytrain, cv=5, scoring='recall').mean()

print("DecisionTreeClassifier Accuracy =", dtc_acc)
print("DecisionTreeClassifier Recall =", dtc_recall)

ValueError: ignored

#Draft for task 7 (not to be considered)

In [100]:
Task7_train_data = pd.read_csv("https://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/train.csv")
Task7_test_data = pd.read_csv("https://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/test.csv")
Task7_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [101]:
Task7_train_data.drop(labels=['Ticket', 'Name', 'PassengerId','Cabin'], axis=1 , inplace = True) # axis 1 = column 0 = row , inplace = whethere to overwrite
Task7_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [102]:
Task7_train_data['Embarked'] = Task7_train_data['Embarked'].astype('category')
Task7_train_data = pd.get_dummies(Task7_train_data, columns=['Embarked'])

Task7_train_data['Sex'] = Task7_train_data['Sex'].astype('category')
Task7_train_data = pd.get_dummies(Task7_train_data, columns=['Sex'])

Task7_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Age         714 non-null    float64
 3   SibSp       891 non-null    int64
 4   Parch       891 non-null    int64
 5   Fare        891 non-null    float64
 6   Embarked_C  891 non-null    uint8
 7   Embarked_Q  891 non-null    uint8
 8   Embarked_S  891 non-null    uint8
 9   Sex_female  891 non-null    uint8
 10  Sex_male    891 non-null    uint8
dtypes: float64(2), int64(4), uint8(5)
memory usage: 46.2 KB

In [103]:
#replace infinite values for Nan and NaN values with the mean:

Task7_train_data.replace([np.inf, -np.inf], np.nan)
Task7_train_data.fillna(Task7_train_data.mean())

     Survived  Pclass        Age  ...  Embarked_S  Sex_female  Sex_male
0           0       3  22.000000  ...           1           0         1
1           1       1  38.000000  ...           0           1         0
2           1       3  26.000000  ...           1           1         0
3           1       1  35.000000  ...           1           1         0
4           0       3  35.000000  ...           1           0         1
..        ...     ...        ...  ...         ...         ...       ...
886         0       2  27.000000  ...           1           0         1
887         1       1  19.000000  ...           1           1         0
888         0       3  29.699118  ...           1           1         0
889         1       1  26.000000  ...           0           0         1
890         0       3  32.000000  ...           0           0         1

[891 rows x 11 columns]

In [116]:
# your answer here

from sklearn.model_selection import train_test_split

# Separate the input and output columns.
Xtrain2 = Task7_train_data.drop('Survived', axis=1)
# For the output, we'll use the Survived column
Ytrain2 = Task7_train_data['Survived']

#no need for split into train and test as we have 2 different datasets

In [117]:
##Verify Data

# summarizes Xtrain, Xtest, Ytrain, Ytest
print(Xtrain2.shape, Ytrain2.shape)

(891, 10) (891,)

In [118]:
from sklearn import tree
from sklearn.model_selection import cross_val_score

dtc = tree.DecisionTreeClassifier()
dtc.fit(Xtrain2, Ytrain2)
dtc_acc = cross_val_score(dtc, Xtrain2, Ytrain2, cv=5, scoring='accuracy').mean()
dtc_recall = cross_val_score(dtc, Xtrain2, Ytrain2, cv=5, scoring='recall').mean()

print("DecisionTreeClassifier Accuracy =", dtc_acc)
print("DecisionTreeClassifier Recall =", dtc_recall)

ValueError: ignored